### ISSUE TITLE
May You Please Add Self Buffs to the Sims?

### ISSUE THREAD

**Issue by SnailRacer-0** [dl-stuff/dl#82]
Just as you've incorporated Team Inspiration and Team Energy into the DPS Simulator, may you also please incorporate _Self_ Inspiration and _Self_ Energy into it?  Each of them plays a role some adventurers' performances such as Yurius (Self Inspiration), Gala Sarisse (Self Energy thanks to her co-ability), and Annelie (Team and Self Energy).  Ignoring these qualities discolors these adventurers' strengths, which is antithetical to the purpose of this sim.  Also, may you please add Taiko Tandem to the list of existing wyrmprints and incorporate Energy-related effects (from wyrmprints and dragons alike) into the sim?  In DPS Distribution, may you please place damage boosts from energized or inspired skills into new sections called Self Energy or Self Inspiration, respectively.  Adding these will be huge steps in the right direction.

  Speaking of buffs, may Self Buffs please be added/conspicuous in the DPS distribution?  I believe that a reasonable person would like to know how much self-buffing skills from Agito weapons impact adventurers' performances.  Plus, in the DPS Description, it's inconsistent not to see Yue's Self Buffs when (some of) Durant's similar Self Buffs are in plain sight.  By the way, calling Durant's buffs _Team Buffs_ isn't wrong, but calling them Self Buffs clarifies that he only improves himself, which some people will appreciate.  I'm confident that that you're capable of implementing these needed updates.

**Comment by Mushymato** [comment]
Buff in general is more accurately expressed as the resulting damage from attacking while under buffs, and the current team dps solution is more of a bandaid solution to not actually implement real team DPS. 

I don't see much point in separating self buffs into their own slice, since they are generally an intrinsic part of the adventurer's kit and many adventurers have buffs in multiple brackets that interact with each other and would be difficult to represent individually. That said, feel free to send in a pull request if you have an implementation in mind.

The examples listed in regards to self energy/inspiration are already implemented and applied to skills as they are used. I am unsure what you mean with Yue/Durant, both of them have self buffs applied as per their kit. You can use the `Log` button on [custom sim](https://wildshinobu.pythonanywhere.com/ui/dl_simc.html) to see what buffs are applied and when.
